#!/usr/bin/python3.5
from tld import get_tld

"""
Script to get country from suffix of top level domain.
Geographically unclear (.net, .com, etc) are filled in manually...
"""

c_list = """http://8sidor.se/
http://aasanetidende.no/
http://alvesta.lokaltidningen.se/
http://arendalstidende.no/
http://www.austagderblad.no/
http://avestatidning.com/
http://avisahemnes.no/
http://avisenagder.no/
http://bastad.lokaltidningen.se/
http://bblat.se/
http://birkenes-avisa.no/
http://bjuv.lokaltidningen.se/
http://boblad.no/
http://bohuslaningen.se/
http://bygdebladet.no/
http://commersen.lokaltidningen.se/
http://dalabygden.se/
http://dalane-tidende.no/
http://ekuriren.se/
http://ekuriren.se/nyheter/strangnas
http://eposten.se/
http://fagersta-posten.se/
http://finansavisen.no/
http://fiskeribladetfiskaren.no/
http://fjell-ljom.no/
http://gastriklandstidning.se/
http://gbnett.no/
http://grannar.no/
http://grenda.no/
http://groruddalen.no/
http://haalogalandavis.no/
http://hallandsposten.se/
http://hallingdolen.no/
http://halmstad.lokaltidningen.se/
http://hassleholm.lokaltidningen.se/
http://helsingborg.lokaltidningen.se/
http://hn.se/
http://hoganas.lokaltidningen.se/
http://ialta.no
http://inderoyningen.no/
http://jbl.no/
http://kavlinge.lokaltidningen.se/
http://kkuriren.se/
http://klt.nu/
http://kristianstad.lokaltidningen.se/
http://landskrona.lokaltidningen.se/
http://lansposten.se/
http://lanstidningen.se/
http://ljungby.lokaltidningen.se/
http://lommabladet.lokaltidningen.se/
http://lt.se/
http://lund.lokaltidningen.se/
http://lyngdalsavis.no/
http://magazin24.se/
http://malmo.lokaltidningen.se/
http://mariestadstidningen.se
http://markbladet.se/
http://melhusporten.no
http://mellanskane.lokaltidningen.se/
http://mitti.se/
http://morgenbladet.no/
http://mre.no/
http://na.se/
http://nattidningenfyren.se/
http://nlt.se/
http://nordrenett.no/
http://norrahalland.se/
http://norran.se/
http://norrteljetidning.se/
http://nwt.se
http://nwt.se/amal/
http://nwt.se/arvika/
http://nwt.se/filipstad/
http://nwt.se/karlskoga-degerfors/
http://nwt.se/kristinehamn/
http://nwt.se/saffle/
http://nwt.se/sunne/
http://nye-troms.no/
http://nyhende.komheim.no/
http://nyhetsbynleksand.se/
http://nynashamnsposten.se/
http://opp.no/
http://ostgota.lokaltidningen.se/
http://oyblikk.no
http://rogalandsavis.no/
http://ryfylke.net/
http://salaallehanda.com/
http://saltenposten.no/
http://sandnesposten.no/
http://selbyggen.no/
http://skaraborgsbygden.se/
http://skillingaryd.nu/
http://sla.se
http://sla.se/hjo/
http://solabladet.no/
http://sormlandsbygden.se/
http://steinkjer-avisa.no/
http://strandbuen.no/
http://stromstadstidning.se/
http://sva.no/
http://svalbardposten.no/
http://svedala.lokaltidningen.se/
http://sverigesradio.se/
http://trelleborg.lokaltidningen.se/
http://ttela.se/
http://tysver-bygdeblad.no/
http://upplandsnyheter.se/
http://varingen.no/
http://varmlandsbygden.se/
http://vastboandan.lokaltidningen.se/
http://vastmanlandsnyheter.se/
http://vaxjo.lokaltidningen.se/
http://velkomne.no/
http://vellinge.lokaltidningen.se/
http://vestavind-sveio.no/
http://vestnesavisa.no/
http://vlt.se/
http://vtb.no/
http://www.aasavis.no/
http://www.adressa.no/
http://www.aftenbladet.no/
http://www.aftenposten.no/
http://www.aftonbladet.se/
http://www.agderposten.no/
http://www.alingsaskuriren.se/
http://www.alingsastidning.se/
http://www.allehanda.se/
http://www.allehanda.se/harnosand
http://www.altaposten.no/
http://www.amliavisa.no/
http://www.amta.no/
http://www.an.no/
http://www.andalsnes-avis.no/
http://www.arbetarbladet.se/
http://www.auraavis.no/
http://www.austagderblad.no/
http://www.austevollforlag.no/
http://www.av-avis.no/
http://www.avisa-hordaland.no/
http://www.avisa-st.no/
http://www.avisa-valdres.no/
http://www.ba.no/
http://www.banett.no/
http://www.barometern.se/
http://www.barometern.se/oskarshamn/
http://www.bjuvsnytt.se/
http://www.bladet.no/
http://www.blekingeposten.se/
http://www.blt.se/
http://www.blv.no/
http://www.bmz.se/
http://www.bomlo-nytt.no/
http://www.bsnett.no/
http://www.bt.no/
http://www.bt.se/
http://www.budstikka.no/
http://www.bygdanytt.no/
http://www.bygdeposten.no/
http://www.corren.se/
http://www.dagbladet.no/
http://www.dagen.no/
http://www.dagen.se/
http://www.dagensperspektiv.no/
http://www.dagensvimmerby.se/
http://www.dagogtid.no/
http://www.dagsavisen.no/
http://www.dalademokraten.se/
http://www.demokraten.no/
http://www.di.se/
http://www.direktpress.se/goteborg
http://www.direktpress.se/vasterastidning
http://www.dn.no/
http://www.dn.se/
http://www.dolen.no/
http://www.drangedalsposten.no/
http://www.driva.no/
http://www.dt.no/
http://www.dt.se/
http://www.dt.se/borlange
http://www.dt.se/hedemora
http://www.dt.se/ludvika
http://www.dt.se/mora
http://www.eikerbladet.no/
http://www.enebakkavis.no/
http://www.eub.no/
http://www.expressen.se/
http://www.expressen.se/gt/
http://www.expressen.se/kvallsposten/
http://www.f-b.no/
http://www.fanaposten.no/
http://www.firda.no/
http://www.firdaposten.no/
http://www.firdatidend.no/
http://www.fjordabladet.no/
http://www.fjordingen.no/
http://www.fjt.no/
http://www.flamman.se/
http://www.folkbladet.nu/
http://www.folkbladet.se/
http://www.folkebladet.no/
http://www.fosna-folket.no/
http://www.framtidinord.no/
http://www.fremover.no/
http://www.fvn.no/
http://www.gat.no/
http://www.gd.no/
http://www.gd.se/
http://www.gjengangeren.no/
http://www.glomdalen.no/
http://www.goteborgsfria.se/
http://www.gp.se/
http://www.h-a.no/
http://www.h-avis.no/
http://www.ha-halden.no/
http://www.hadeland.no/
http://www.hallekis.com/
http://www.hardanger-folkeblad.no/
http://www.hblad.no/
http://www.hd.se/
http://www.helagotland.se/
http://www.helahalsingland.se/
http://www.helahalsingland.se/bollnas/
http://www.helahalsingland.se/ljusdal/
http://www.helahalsingland.se/soderhamn/
http://www.helg.no/
http://www.hf.no/
http://www.hitra-froya.no/
http://www.hoglandsnytt.se/
http://www.ht.no/
http://www.idag.no/
http://www.indre.no/
http://www.innherred.no/
http://www.itromso.no/
http://www.jarlsbergavis.no/
http://www.jnytt.se/
http://www.jp.se/
http://www.kanalen.no/
http://www.kindaposten.se/
http://www.klartale.no/
http://www.klassekampen.no/
http://www.kristianstadsbladet.se/
http://www.kungalvsposten.se/
http://www.kungsbackaposten.se/
http://www.kuriren.nu/
http://www.kv.no/
http://www.kvinnheringen.no/
http://www.kystogfjord.no/
http://www.l-a.no/
http://www.laagendalsposten.no/
http://www.laholmstidning.se/
http://www.landskronadirekt.com/
http://www.lerumstidning.se/
http://www.lidkopingsnytt.nu/
http://www.lierposten.no/
http://www.lindenytt.com/
http://www.lister24.no/
http://www.lofot-tidende.no/
http://www.lofotposten.no/
http://www.lokalavisa.as/
http://www.lp.no/
http://www.ltz.se/
http://www.lysekilsposten.se/
http://www.mb.no/
http://www.meloyavisa.no/
http://www.metro.se/
http://www.midtsiden.no/
http://www.miljomagasinet.se/
http://www.molndalsposten.se/
http://www.morenytt.no/
http://www.moss-avis.no/
http://www.mvt.se/
http://www.namdalsavisa.no/
http://www.nationen.no/
http://www.nettavisen.no/
http://www.noblad.no/
http://www.nord-salten.no/
http://www.norddalen.no/
http://www.nordhordland.no/
http://www.nordlys.no/
http://www.nrk.no/buskerud/
http://www.nrk.no/finnmarkslopet/
http://www.nrk.no/ho/
http://www.nrk.no/hordaland/
http://www.nrk.no/mr/
http://www.nrk.no/nordland/
http://www.nrk.no/nordnytt/
http://www.nrk.no/ostafjells/
http://www.nrk.no/ostfold/
http://www.nrk.no/ostlandssendingen/
http://www.nrk.no/rogaland/
http://www.nrk.no/sapmi/
http://www.nrk.no/finnmark/
http://www.nrk.no/sognogfjordane/
http://www.nrk.no/sorlandet/
http://www.nrk.no/telemark/
http://www.nrk.no/trondelag/
http://www.nrk.no/vestfold/
http://www.nrk.no/troms/
http://www.nsd.se/
http://www.nsk.se/
http://www.nt.se/
http://www.nvnytt.no/
http://www.nvp.se/
http://www.nytid.no/
http://www.oa.no/
http://www.oblad.no/
http://www.olandsbladet.se/
http://www.op.no/
http://www.op.se/
http://www.opdalingen.no/
http://www.orusttjorntidningen.se/
http://www.osogfusa.no/
http://www.osthammarsnyheter.se/
http://www.ostlendingen.no/
http://www.ostrasmaland.se/
http://www.oyene.no/
http://www.oyposten.no/
http://www.p4.no/
http://www.partilletidning.se/
http://www.pd.no/
http://www.pt.se/
http://www.r-a.no/
http://www.ranablad.no/
http://www.raumnes.no/
http://www.rb.no/
http://www.rbnett.no/
http://www.realtid.se/
http://www.retten.no/
http://www.rha.no/
http://www.ringblad.no/
http://www.ringsaker-blad.no/
http://www.sa.no/
http://www.sagat.no/
http://www.sandeavis.no/
http://www.sb.no/
http://www.skanesfria.se/
http://www.skaraborgslanstidning.se/
http://www.skargarden.se/
http://www.skd.se/
http://www.skovdenyheter.se/
http://www.smaalenene.no/
http://www.smalandsdagblad.se/
http://www.smalanningen.se/
http://www.smbt.se/
http://www.smp.no/
http://www.smp.se/
http://www.sn.se/
http://www.sognavis.no/
http://www.sovesten.no/
http://www.st.nu/
http://www.stockholmdirekt.se
http://www.stockholmdirekt.se/enahabo/
http://www.stockholmdirekt.se/kista-rinkeby-tensta/
http://www.stockholmdirekt.se/malarotidning/
http://www.stockholmdirekt.se/sodrasidan/
http://www.stockholmdirekt.se/tabynyheter/
http://www.stockholmdirekt.se/viisolna/
http://www.stockholmsfria.se/
http://www.strilen.no/
http://www.suldalsposten.no/
http://www.sunnhordland.no/
http://www.sunnmoringen.no/
http://www.svd.se/
http://www.svelviksposten.no/
http://www.svt.se/nyheter/lokalt/blekinge/
http://www.svt.se/nyheter/lokalt/dalarna/
http://www.svt.se/nyheter/lokalt/gavleborg/
http://www.svt.se/nyheter/lokalt/halland/
http://www.svt.se/nyheter/lokalt/helsingborg/
http://www.svt.se/nyheter/lokalt/jamtland/
http://www.svt.se/nyheter/lokalt/jonkoping/
http://www.svt.se/nyheter/lokalt/norrbotten/
http://www.svt.se/nyheter/lokalt/orebro/
http://www.svt.se/nyheter/lokalt/ost/
http://www.svt.se/nyheter/lokalt/skane/
http://www.svt.se/nyheter/lokalt/smaland/
http://www.svt.se/nyheter/lokalt/sodertalje/
http://www.svt.se/nyheter/lokalt/sormland/
http://www.svt.se/nyheter/lokalt/stockholm/
http://www.svt.se/nyheter/lokalt/uppsala/
http://www.svt.se/nyheter/lokalt/varmland/
http://www.svt.se/nyheter/lokalt/vast/
http://www.svt.se/nyheter/lokalt/vasterbotten/
http://www.svt.se/nyheter/lokalt/vasternorrland/
http://www.svt.se/nyheter/lokalt/vastmanland/
http://www.sydnarkenytt.se/
http://www.sydostran.se/
http://www.sydsvenskan.se/
http://www.sydvesten.no/
http://www.synste.no/
http://www.t-a.no/
http://www.ta.no/
http://www.tb.no/
http://www.telen.no/
http://www.tk.no/
http://www.tranas-posten.se/
http://www.tranastidning.se/
http://www.trelleborgsallehanda.se/
http://www.tronderbladet.no/
http://www.tv2.no/
http://www.tv4.se/nyheterna
http://www.tvedestrandsposten.no/
http://www.tysnesbladet.no/
http://www.unt.se/
http://www.unt.se/sigtunabygden/
http://www.uppsalatidningen.se/
http://www.ut.se/
http://www.vaksdalposten.no/
http://www.varden.no/
http://www.vastgotabladet.se/
http://www.vaxjobladet.se/
http://www.venneslatidende.no/
http://www.vestbyavis.no/
http://www.vestnytt.no/
http://www.vetlandaposten.se/
http://www.vf.se/
http://www.vg.no/
http://www.vikebladet.no/
http://www.vimmerbytidning.se/
http://www.vk.se/
http://www.vl.no/
http://www.vn.se/
http://www.vol.no/
http://www.vt.se/
http://www.ystadsallehanda.se/
http://ystad.lokaltidningen.se/
http://ytringen.no/
https://frostingen.no/
http://nwt.se/bengtsfors/
http://www.altinget.dk
http://www.avisen.dk
http://www.b.dk
http://www.bt.dk
http://tidende.dk/
http://www.borsen.dk
http://www.arbejderen.dk
http://www.information.dk
http://sn.dk/koege
http://www.licitationen.dk
http://sn.dk/ringsted
http://sn.dk/roskilde
http://www.dagensmedicin.dk
http://www.danskekommuner.dk
http://denkorteavis.dk
http://dknyt.dk/
http://www.dr.dk/p4bornholm
http://www.dr.dk/p4esbjerg
http://www.dr.dk/p4fyn
http://www.dr.dk/p4kbh
http://www.dr.dk/ligetil
http://www.dr.dk/p4vest
http://www.dr.dk/p4nord
http://www.dr.dk/nyheder/
http://www.dr.dk/p4sjaelland
http://www.dr.dk/p4syd
http://www.dr.dk/p4trekanten
http://www.dr.dk/p4aarhus
http://www.ekstrabladet.dk
http://energiwatch.dk
http://www.business.dk
http://erhvervsavisen.dk/
http://finans.dk/
http://finanswatch.dk
http://www.fla.de
http://frdb.dk
http://sn.dk/nordsjaelland
http://nordjyske.dk/nyheder/frederikshavn
http://www.fyens.dk
http://fodevarewatch.dk
http://haberler.dk/tr/
http://www.helsingordagblad.dk/
http://aoh.dk
http://nordjyske.dk/nyheder/hjoerring
http://hsfo.dk
http://www.husforbi.dk
http://ing.dk
http://nordjyske.dk/nyheder/jammerbugt
http://www.jv.dk
http://jyllands-posten.dk
http://www.kanukoka.gl
http://www.kidsnews.dk
http://www.kristeligt-dagblad.dk
http://www.idag.dk
http://lokalavisen.dk
http://folketidende.dk
http://koege.lokalavisen.dk
https://www.mm.dk
http://dinby.dk/mariager-avis
http://nordjyske.dk/nyheder/mariagerfjord
http://mediawatch.dk
http://medwatch.dk
http://www.mx.dk/
http://mja.dk
http://modkraft.dk
http://newsbreak.dk
http://nordjyske.dk/nyheder/nordjylland
http://nordjyske.dk/
http://sn.dk/nordvestsjaelland
http://www.skive-her.dk
http://politiken.dk
http://amtsavisen.dk
http://nordjyske.dk/nyheder/rebild
http://sermitsiaq.ag
http://sn.dk
http://www.skivefolkeblad.dk
http://sn.dk/alleroed
http://sn.dk/furesoe
http://sn.dk/egedal
http://sn.dk/faxe
http://sn.dk/fredensborg
http://sn.dk/frederikssund
http://sn.dk/gribskov
http://sn.dk/halsnaes
http://sn.dk/helsingoer
http://sn.dk/hilleroed
http://sn.dk/hoersholm
http://sn.dk/lejre
http://sn.dk/rudersdal
http://sn.dk/slagelse
http://sn.dk/stevns
https://www.statstidende.dk
http://www.saebyavis.dk
http://sondagsavisen.dk
http://cphpost.dk
http://nordjyske.dk/nyheder/thisted
http://www.tvmidtvest.dk
http://www.tvsyd.dk
http://www.tveast.dk
http://www.tv2bornholm.dk
http://www.tv2fyn.dk
http://www.tv2lorry.dk
http://www.tv2nord.dk
http://nyheder.tv2.dk
http://www.tv2oj.dk/nyheder
http://udfordringen.dk
http://ugeavisen.dk
http://sn.dk/vordingborg
http://sn.dk/ugebladetvestsjaelland
http://gribskov.lokalavisen.dk
http://dinby.dk/ugeposten-skjern
http://minby.dk/valby-bladet/
http://www.vamdrup.dk/news
http://minby.dk/vanloese-bladet/
http://vafo.dk
http://sn.dk/vestegnen
http://minby.dk/vesterbro-bladet/
http://nordjyske.dk/nyheder/vesthimmerland
http://www.vesthimmerlandsavis.dk
http://dinby.dk/viborg-nyt
http://viborg-folkeblad.dk
http://gentofte.lokalavisen.dk
http://dinby.dk/vinderup-avis
http://www.weekendavisen.dk
http://www.oestbirk-avis.dk
http://minby.dk/oesterbro-avis/
http://oehf.dk/
http://nordjyske.dk/nyheder/aalborg
http://dinby.dk/aarhus-onsdag
http://stiften.dk/
http://www.aarsavis.dk
http://ebeltoft.lokalavisen.dk
http://syddjurs.lokalavisen.dk/
http://albertslund.lokalavisen.dk
http://alleroed.lokalavisen.dk
http://www.aok.dk
http://minby.dk/amagerbladet/
http://ballerupbladet.dk/
http://bornholm.nu/
http://www.brandebladet.dk
http://nordjyske.dk/nyheder/broenderslev
http://bha.dk/
http://sn.dk/holbaek
http://minby.dk/city-avisen/
http://dagbladet-holstebro-struer.dk/
http://dagbladetringskjern.dk/
http://www.nordschleswiger.dk
http://www.lyngby-taarbaek.lokalavisen.dk
http://dinavis.lokalavisen.dk
http://dinby.dk/djurslandsposten
http://dragoer-nyt.dk/
http://dinby.dk/ebeltoft-folketidende
http://www.farsoavis.dk
http://dinby.dk/favrskov-avisen
http://favrskov.lokalavisen.dk
http://fjendsfolkeblad.dk/
http://dinby.dk/folkebladet-djursland
http://folkebladet.dk
http://folkebladetlemvig.dk/
http://minby.dk/frederiksberg-bladet/
http://frederikssund.lokalavisen.dk
http://dinby.dk/frederiksvaerk-ugeblad
http://furesoe.lokalavisen.dk/
http://www.fyens.dk/assens
http://www.fyens.dk/faaborg-midtfyn
http://www.fyens.dk/kerteminde
http://www.fyens.dk/langeland
http://www.fyens.dk/middelfart
http://www.fyens.dk/nordfyn
http://www.fyens.dk/nyborg
http://www.fyens.dk/odense
http://www.fyens.dk/svendborg
http://www.fyens.dk/aro
http://www.galtenfolkeblad.dk
http://www.gladsaxebladet.dk
http://dinby.dk/grenaa-bladet
http://graastenavis.dk
http://www.gudenaadalens-avis.dk
http://halsnaes.lokalavisen.dk
http://www.hasserisavis.dk
http://hilleroed.lokalavisen.dk
http://dinby.dk/holstebro-onsdag
http://hvidovre.lokalavisen.dk
http://aoib.dk
http://sn.dk/kalundborg
http://www.kjavis.dk
http://aabenraa.lokalavisen.dk
http://aarhus.lokalavisen.dk
http://aarhusmidt.lokalavisen.dk
http://aarhusnord.lokalavisen.dk
http://aarhussyd.lokalavisen.dk
http://aarhusvest.lokalavisen.dk
http://egedal.lokalavisen.dk
http://esbjerg.lokalavisen.dk
http://fredericia.lokalavisen.dk
http://frederikssund.lokalavisen.dk
http://grenaa.lokalavisen.dk
http://haderslev.lokalavisen.dk
http://hornsherred.lokalavisen.dk
http://horsens.lokalavisen.dk
http://kaloevig.lokalavisen.dk
http://kolding.lokalavisen.dk
http://dinby.dk/lokalavisen-lemvig
http://norddjurs.lokalavisen.dk
http://www.nsnet.dk/
http://odense.lokalavisen.dk
http://skanderborg.lokalavisen.dk
http://sn.dk/sydkysten
http://soenderborg.lokalavisen.dk
http://sn.dk/taastrup
http://fredensborg.lokalavisen.dk
http://varde.lokalavisen.dk
http://vejle.lokalavisen.dk
http://www.lyngposten.dk
http://www.folkebladet.info
http://vafo.dk/
http://sn.dk/heden
http://www.midtvendsysselavis.dk/
http://nordjyske.dk/nyheder/morsoe/
http://www.nibeavis.dk
http://naestved-bladet.dk
http://minby.dk/noerrebronordvest-bladet/
http://dinby.dk/randers-onsdag
http://roskilde.lokalavisen.dk
http://rudersdal.lokalavisen.dk/
http://www.rnn.dk
http://sallingavis.dk
http://www.samso.dk/
http://www.skagensavis.dk
http://sn.dk/solroed
http://sn.dk/soroe
http://stevnsbladet.dk
http://sn.dk/greve
http://sn.dk/ishoej
http://www.sydtid.dk
http://dinby.dk/ugebladet-skanderborg
http://ugeavisenkarup.dk
http://dinby.dk/ugeavisen-moeldrup-aalestrup
http://ugeavisen-odense.dk
http://sn.dk/odsherred
http://dinby.dk/ugeavisen-ringkoebing
http://dinby.dk/ugeavisen-struer
http://ugeavisensvendborg.dk
http://www.uge-avisen.net
http://hoersholm.lokalavisen.dk
http://sn.dk/naestved"""

co = {
    "no": "norway",
    "se": "sweden",
    "dk": "denmark"

}

for c in c_list.split("\n"):
    suffix = get_tld(c).split(".")[1]
    print(co.get(suffix, "??"))
